// display functionality code starts on line 145
const affirmationsList = [
    {   "id" : 1,
        "affirmation" : "You got this!",
    },
    {   "id" : 2,
        "affirmation" : "You'll figure it out.",
    },
    {   "id" : 3,
        "affirmation" : "You're a smart cookie.",
    },
    {   "id" : 4,
        "affirmation" : "Your mind is full of brilliant ideas.",
    },
    {   "id" : 5,
        "affirmation" : "Sucking at something is the first step towards being good at something.",
    },
    {   "id" : 6,
        "affirmation" : "Everything has cracks - that's how the light gets in!",
    },
    {   "id" : 7,
        "affirmation" : "Mistakes don't make you less capable.",
    },
    {   "id" : 8,
        "affirmation" : "We are all works in progress.",
    },
    {   "id" : 9,
        "affirmation" :  "You are a capable human.",
    },
    {   "id" : 10,
        "affirmation" :  "You know more than you think.",
    },
    {   "id" : 11,
        "affirmation" : "Give yourself space to grow and learn.",
    },
    {   "id" : 12,
        "affirmation" : "If everything was easy, you'd be bored.",
    },
    {   "id" : 13,
        "affirmation" : "You are admirable for taking this on.",
    },
    {   "id" : 14,
        "affirmation" : "You are resourceful and clever.",
    },
    {   "id" : 15,
        "affirmation" : "You will find a way.",
    },
    {   "id" : 16,
        "affirmation" : "You are becoming closer to your true self every day.",
    },
    {   "id" : 17,
        "affirmation" : "Struggling means you're learning.",
    },
    {   "id" : 18,
        "affirmation" : "You're doing a great job.",
    },
    {   "id" : 19,
        "affirmation" : "It'll feel magical when it's working",
    },
    {   "id" : 20,
        "affirmation" : "You have more people rooting for your success than you know.",
    },
    {   "id" : 21,
        "affirmation" : "You make a difference in the world by simply existing in it",
    },
    {   "id" : 22,
        "affirmation" : "Trust that you are on the right path.",
    },
    {   "id" : 23,
        "affirmation" : "You are learning valuable lessons from yourself every day.",
    },
    {   "id" : 24,
        "affirmation" : "You are worthy and deserving of respect.",
    },
    {   "id" : 25,
        "affirmation" : "You know more today than you knew yesterday.",
    },
    {   "id" : 26,
        "affirmation" : "You are an inspiration.",
    },
    {   "id" : 27,
        "affirmation" : "Your life is already a miracle of chance waiting for you to shape its destiny.",
    },
    {   "id" : 28,
        "affirmation" : "Your life is about to be incredible.",
    },
    {   "id" : 29,
        "affirmation" : "Nothing is impossible. The word itself says 'I’m possible!'",
    },
    {   "id" : 30,
        "affirmation" : "Failure is just another way to learn how to do something right.",
    },
    {   "id" : 31,
        "affirmation" : "Give yourself permission to do what is right for you.",
    },
    {   "id" : 32,
        "affirmation" : "Life is not a sprint; it's a marathon. Take it one step at a time.",
    },
    {   "id" : 33,
        "affirmation" : "Success is the progressive realization of a worthy goal.",
    },
    {   "id" : 34,
        "affirmation" : "People with goals succeed because they know where they’re going.",
    },
    {   "id" : 35,
        "affirmation" : "All you need is the plan, the roadmap, and the courage to press on to your destination.",
    },
    {   "id" : 36,
        "affirmation" : "The opposite of courage in our society is not cowardice...it is conformity.",
    },
    {   "id" : 37,
        "affirmation" : "Whenever we’re afraid, it’s because we don’t know enough. If we understood enough, we would never be afraid.",
    },
    {   "id" : 38,
        "affirmation" : "The past does not equal the future.",
    },
    {   "id" : 39,
        "affirmation" : "The path to success is to take massive, determined action.",
    },
    {   "id" : 40,
        "affirmation" : "It’s what you practice in private that you will be rewarded for in public.",
    },
    {   "id" : 41,
        "affirmation" : "Small progress is still progress, and worth celebrating.",
    },
    {   "id" : 42,
        "affirmation" : "Don't worry if you find flaws in your past creations; it's because you've evolved.",
    },
    {   "id" : 43,
        "affirmation" : "Starting is the most difficult step - but you can do it!",
    },
    {   "id" : 44,
        "affirmation" : "Don't forget to enjoy the journey.",
    },
    {   "id" : 45,
        "affirmation" : "It's not a mistake, it's a learning opportunity.",
    },
]

// sources: 
// https://github.com/annthurium/affirmations/blob/master/affirmations.js
// https://theblissfulmind.com/positive-affirmations-list/


const affirmationsDisplay = document.getElementById("affirmationsDisplayUL")

const displayAffirmation = () => {    
    const affirmations = affirmationsList[Math.floor(Math.random() * affirmationsList.length)]
    
    const affirmationsItem = `
                            <h2 id="affirmationsItems">
                            <strong>-Affirmation-</strong><br />
                            <em>${affirmations.affirmation}</em> 
                            </h2>
                            `
    affirmationsDisplay.innerHTML = affirmationsItem
}

displayAffirmation()

const refreshAffirmationDisplay = () => {
    window.setInterval(function() { displayAffirmation() }, 15000)
}

refreshAffirmationDisplay()

